### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by carolsinc** [carolsinc/web-design-2-independent-project#2]
I have a hidden check box for my mobile navigation, but markbot doesn't want it hidden, is there an alternative to showing the check box that is still accessible?

@hellachella 
@HannahDelaney

**Comment by HannahDelaney** [comment]
I had a quick look, and I'm not sure if you've updated recently but the line in question when this is put through Markbot for me (Line 23) has a typing error?

It says `<label class="nav-label" for="nfavicon.icoav-check">` and I think the favicon.ivo bit in the middle was an accident. Let me know if that helps or if you still have the same Markbot issue.

**Comment by carolsinc** [comment]
Now it's telling me I need a label

@HannahDelaney

**Comment by HannahDelaney** [comment]
So it is. That's annoying!

I'm missing something here, as far as I can tell what you have should be working. I'll find a solution!

**Comment by carolsinc** [comment]
You are the best!

**Comment by HannahDelaney** [comment]
Okay. So because the navigation needs to be visible to a screen reader for accessibility, there has to be some sort of readable content in there. If you add an aria-label to the `<label>` it should work. Something like "Click to open navigation" would be a good option. Then someone using VoiceOver or similar, or tabbing through the site, will be able to understand what that input is for/where to find the menu.

I definitely should have pegged that faster ..

**Comment by carolsinc** [comment]
NAILED IT!
